### ISSUE TITLE
Which specs are expected to be written?

### ISSUE THREAD

**Issue by phochste** [MellonScholarlyCommunication/spec-overview#1]
As discussed in the 2021-05-03 meeting:

- [x] Orchestrator
- [x] Policy language
- [x] Declaration of result rules (e.g. addToEventLog, sendNotification)
- [ ] Event log
- [ ] Pod structure

**Comment by mielvds** [comment]
overview page + repositories (except for data pod; @Dexagod not sure where you wanted to start...I can still create one).
Results can be seen here: https://mellonscholarlycommunication.github.io/spec-overview/

**Comment by Dexagod** [comment]
I'll start with the event log spec
