### ISSUE TITLE
We need a better definition for a Maintainer

### ISSUE THREAD

**Issue by phochste** [MellonScholarlyCommunication/spec-overview#10]
Currently the [Maintainer](https://mellonscholarlycommunication.github.io/spec-overview/#maintainer) is defined in the spec-overview as:

> A human agent that can manually perform actions on the network using a dashboard application.
> 
> Usually a person employed by an organisation (e.g., a Cultural Heritage Institution) to maintain data and datasets owned by that organisation.

The use of Maintainer is used differently in separate specs.

**Orchestator**

In the [Orchestrator](https://mellonscholarlycommunication.github.io/spec-orchestrator/) spec a Maintainer is the a person that owns uses a Datapod to disseminate artefacts on the network.

- The Maintainer informs other actors in the network about actions on the pod
- In section 5.2 the Maintainer is part of het pod network, but is not mentioned in the Service Hub network
- An Orchestrator works in behalf of the Maintainer (of the pod)

Exceptions:

- In section 7.1 it is sugggested that policy documents are stored in a container `This container can be under the controll of the Orchestrator or a Data Pod/Service Hub maintainer`. Here the term  *Maintainer* is used also for a Service Hub. (Note: this is an error?)

- In section 8.2 the maintainers mentioned are again about the pod (not the service hub)

**Data pod**

No mention of *Maintainer*.

**Rule language**

No mention of *Maintainer*.

**Artefact Lifecycle Event Log**

`dean:Maintainer` is defined as a `A Actor, Maintainer and Human Agent that participates on the network and generates activities pertaining to the lifecycle of an Artefact.` 3 different roles:

- The maintainer of the pod
- The actor on the Service Hub that executed the service
- The actor that owns the event log

**Notifications**

Section 4: the *Maintainer* is the owner of the data pod, but not mentioned for the Service Hub.

> Interaction is thus possible between two maintainers, between two service hubs or between a maintainer and a service hub. 

Exception in Section 5.4: the *Maintainer* is again unclear if it is about a pod maintainer or a actor in a Service Hub:

```
Both the target and actor MUST be identifyable with an HTTP [URI], which SHOULD be a WebID. They MUST be of the following type:

as:Service in case the receiving actor is a Service Hub;

as:Person, as:Organization, or as:Application in case the receiving actor is a Maintainer and an individual, organization, or a software application, respectively.
```

E.g. using the examples 671 this would imply that the `Meemoo` is a maintainer.

Section 6: mentions *Maintainer* **OR** *Service Hub*

Section 7: mentions *Maintainer* as different from *Service Hub*

**Collector**

No mention of *Maintainer*.

**Comment by mielvds** [comment]
Thanks @phochste for this overview. I think most of the confusion comes from the word maintainer, which is useful is many contexts. In summary, the specs attempt to distinguish the following:

- an actor that is a Service Hub (currently: Service Hub)
- some human that works at the Service Hub and can trigger things (currently: not sure, but probably Maintainer of Service Hub)
- an actor that is not a Service Hub, but some entity (person, organization) you can address in notifications and can generate Lifecycle Events (currently: Maintainer)
- some human that is represented digitally by the entity above (eg. the real Bob, or Robert, who is in charge of the network communication at his museum) and can trigger things by operating the dashboard (currently: also Maintainer I'm afraid)

**Comment by phochste** [comment]
We are missing the role of a Creator or RightsHolder who holds the intellectual property of a resource. This is something on a meta level which can't be figured out by a computer. This is information that needs to be added by agreements.

All the CRUD operations on pods, Service Hubs can easily be recorded by machines. At any point in time it is exactly known which agent (webid) created,updated, deleted and even read (something we are missing in the notifications) a resource. Based on these CRUD operations one can generate a part of archival type digital provenance actions that were done to a resource.

What is missing is what is happening on a higher intellectual level to the abstract entity "the artefact" (whatever we mean by that). Who is the Creator/RightsHolder of an artefact can't in general be figured out from looking at who did all CRUD operations. 

In case of Service Hubs, e.g. publishing, on CRUD level you see  "Dave the designer" , "Mary the editor", "Nancy the art director" , "Frank the typesetter", "Publishing department XYZ of Journal Y" ,..etc all working on resources that are part of the new published artefact .. in archival context those are the ones that generate a digital trail of provenance events. These agents trigger CRUD events

But, at a higher level: which entity puts all this work together and says "I announce the published version of preprint XYZ"? This is not Dave, not Mary, Nancy, Frank or even the department XYZ: it is Journal Y. It is an abstract entity on whose name all this is done. This is an other type of lifecycle events than tracing the CRUD level digital provenance. These abstract agents trigger Value added lifecycle events. 

It is _agents who can Write,Append,Control things on Pods_ versus _agents that put their name/rights/label on all the work that has been done._ 

BTW this generates also the complexity what should happen when two Creators/Rightsholders are working together on an artefact. This is certainly something that can't be traced by looking at CRUD operations on one Pod or even looking at the `/profile/card#me` of a Pod.

PS> not that Creator/Rightsholder is a good term for this second type of agent..it comes also with semantic baggage..

**Comment by mielvds** [comment]
> We are missing the role of a Creator or RightsHolder who holds the intellectual property of a resource. This is something on a meta level which can't be figured out by a computer. This is information that needs to be added by agreements.
> 
> All the CRUD operations on pods, Service Hubs can easily be recorded by machines. At any point in time it is exactly known which agent (webid) created,updated, deleted and even read (something we are missing in the notifications) a resource. Based on these CRUD operations one can generate a part of archival type digital provenance actions that were done to a resource.
> 
> What is missing is what is happening on a higher intellectual level to the abstract entity "the artefact" (whatever we mean by that). Who is the Creator/RightsHolder of an artefact can't in general be figured out from looking at who did all CRUD operations.

Agreed, but I wonder if that is something we should be dealing with in this project. But it makes sense if you want the CH/SC use cases to work. Perhaps grouping requirements in 'archieving technical interop' and 'achieving proces interop' might help the discussion.

> 
> In case of Service Hubs, e.g. publishing, on CRUD level you see "Dave the designer" , "Mary the editor", "Nancy the art director" , "Frank the typesetter", "Publishing department XYZ of Journal Y" ,..etc all working on resources that are part of the new published artefact .. in archival context those are the ones that generate a digital trail of provenance events. These agents trigger CRUD events
> 
> But, at a higher level: which entity puts all this work together and says "I announce the published version of preprint XYZ"? This is not Dave, not Mary, Nancy, Frank or even the department XYZ: it is Journal Y. It is an abstract entity on whose name all this is done. This is an other type of lifecycle events than tracing the CRUD level digital provenance. These abstract agents trigger Value added lifecycle events.
> 
> It is _agents who can Write,Append,Control things on Pods_ versus _agents that put their name/rights/label on all the work that has been done._

Jep. There are agents who CRUD things, communicate things and valuate things.
A few thoughts:
- the term Maintainer refers to the actor that is not a service hub itself, but requests services from service hubs. All else needs a new/different name
- within the scope of the project, do we need to concern ourselves with agents that do not need to be addressable and/or identifieable(WebID) in order to make the network interaction work? 

> 
> BTW this generates also the complexity what should happen when two Creators/Rightsholders are working together on an artefact. This is certainly something that can't be traced by looking at CRUD operations on one Pod or even looking at the `/profile/card#me` of a Pod.
> 
> PS> not that Creator/Rightsholder is a good term for this second type of agent..it comes also with semantic baggage..

**Comment by mielvds** [comment]
Maybe we should look at the terms `Actor` vs. `Agent` as well: what's the exact distinction?
At the moment:
- An Actor is a real-world entity that cannot participate in the network because it's not digital; eg. the actual researcher, the organisation running a repository or Cultural Heritage institution. 
- An Agent is a "digital twin" of an Actor; some piece of software, driven by manual or automated triggers, that can create and send notifications, eg. the dashboard, the Service Hub application, the orchestrator,...

**Comment by mielvds** [comment]
@phochste can we use 'custodian' as one of the maintainers?

**Comment by phochste** [comment]
I think that we need to keep to differentiate between the `Actor` and `Agent` indeed. The term `Custodian` is in this context used a generic term for the researcher on the pod, or archivist ? E.g.

| Pod | Service Hub |
|-----|-------------|
| Custodian | Service Provider |

**Comment by mielvds** [comment]
Yes; basically, although we could still use maintainer for that if freed up everywhere else.
In the end it would be a matrix like:

|  | Pod | Service Hub |
|----|-----|-------------|
| **Actor** | Custodian | Service Provider |
| **Agent**| Dashboard / Orchestrator | Orchestrator / ?? |

PS: I feel like I might have switched actor and agent..., but not sure. They are so close. Maybe we need just one word, like  [prov:Agent](https://www.w3.org/TR/prov-o/#Agent)
