### ISSUE TITLE
Do we still need the App role?

### ISSUE THREAD

**Issue by phochste** [MellonScholarlyCommunication/spec-overview#11]
In the [Overview](https://mellonscholarlycommunication.github.io/spec-overview/) spec the **App** is defined as:

```
An App is an autonomous agent dedicated to an actor that hosts a data pod. The App can write to the data pod unsupervised by the human agent and is not limited to the inbox or artefact lifecycle event log.
```

The App is envisioned as a separate component from the Orchestrator that also can access the Rule Book and implement changes to the Data pod independent from the actions of the Orchestrator. 

Is this role not taken over by the orchestrator with our current insights? The App is not mentioned in any of the other specs. More generally there is an offline discussion if it is even desirable to have a seperate software entity that executes the Rule Book : the "can there be more than one orchestrator" discussion.

**Comment by mielvds** [comment]
No, it's irrelevant for achieving interoperability, so I'd remove it. That said, it is something most implementations would need, so perhaps if we ever write something like an implementation guide, we should mention it.

**Comment by mielvds** [comment]
@phochste close this one?
