### ISSUE TITLE
What are these specs about?

### ISSUE THREAD

**Issue by mielvds** [MellonScholarlyCommunication/spec-overview#4]
This collection of protocols is about establishing decentralized networks based on Solid where artefacts and artefact lifecycle information can be exchanged, regardless of the domain or use case.

For the sake of consistency, we should provide a general description on what these 'generic' specs can be used for. I mention it a couple of times in the documents, but it's not very consistent. Some examples from documents:
- facilitate the implementation of a decentralized data exchange ecosystem using Solid
- Protocols and components for generic decentralized artefact exchange networks
- decentralized Web network
- ...

**Comment by pheyvaer** [comment]
As a first step here: could we maybe already add links to all the others specs in the README?

**Comment by mielvds** [comment]
Sure, although this is already in the rendered document as well. 
That said, this issue is about something else: how we are going to call what we are facilitating here. And then align the specs' text with this definition.
