### ISSUE TITLE
Are the Rules and Inbox necesearily part of the Data Pod or can they exist as separate resources?

### ISSUE THREAD

**Issue by mielvds** [MellonScholarlyCommunication/spec-overview#5]

**Comment by phochste** [comment]
Inboxes: what stops them from being on other separate resource? Not able to discover the Inbox for an actor, pod, artefact, project?

Rules: Herbert envisioned rules that are on actor, faculty , institution ,...level so I guess there too

**Comment by mielvds** [comment]
I found this issue in the document; not sure who added it. I agree with you though: they could be hosted anywhere and by anything.

**Comment by mielvds** [comment]
I think we can resolve this as: yes, they can be a separate resource.
