### ISSUE TITLE
Determine labels for specs

### ISSUE THREAD

**Issue by pheyvaer** [MellonScholarlyCommunication/spec-overview#6]
- discussion
- question
- enhancement
- priority-high
- priority-medium
- priority-low

**Comment by pheyvaer** [comment]
@phochste What do you think about these labels for the specs? To start with. We can add more of course later when needed.

**Comment by phochste** [comment]
Looks good!

**Comment by pheyvaer** [comment]
https://github.com/MellonScholarlyCommunication/spec-overview/blob/master/README.md#labels
