### ISSUE TITLE
Is the Service Hub an Solid App/Pod ?

### ISSUE THREAD

**Issue by phochste** [MellonScholarlyCommunication/spec-overview#9]
As discussed in the 2021-11-23 meeting, there was a discussion if a Service Hub should be defined as a Solid App (a client that can talk the Solid protocol), or a Solid Pod in a more extreme case.

This is for me not clear why this is an immediate requirement, rather than that we must prove that it can't be anything else than a Solid App/Pod. The jury is still out.

As far as the experiment and the thinking goes in the current form:

_Notifications_

- The Service Hub must be an LDN Receiver (for incoming notifications)
- The Service Hub must be an LDN Sender (for outgoing notifications)
- The Service Hub has no requirements to read other LDN inboxes (not a Consumer)

_Event log_

- The Service Hub must have an Artefact Event Log implementation (where the protocol requirements still need to be discussed).

_Artefacts_

- Extra requirements on the artefacts due to the protocols used?

**Comment by RubenVerborgh** [comment]
Not having been part of the discussion, I just want to highlight this seems to be a false dichotomy.
Something can be both an app/client and a Pod.

i.e., "client" is a role rather than an absolute entity, as is the case with HTTP and in particular proxies: https://rubenverborgh.github.io/WebFundamentals/architecture/#client-server-relative

**Comment by phochste** [comment]
Indeed it is a false dichotomy. What I meant was that the defining a Service Hub as a Solid App was too vague what this means for implementers of a Service Hub in the context of the Mellon/Erfgoed proposed service model. 

What roles should the Service Hub play is indeed a better question.

**Comment by mielvds** [comment]
It's not vague in the sense that you're demanding all Service Hubs to be able to read (and write) data to a Solid Data Pod. The burden of defining this is with the Solid people like @RubenVerborgh. But I agree that this probably entails more than what's strictly necessary. Finding out the requirements is a good idea.

That said, a Service Hub implementer needs to know what to comply to, so not defining it as a Solid App or [LDP Client ](https://www.w3.org/TR/ldp/#ldp-client)puts the burden on us to specify exactly what it should or should not be able to do. Listing roles is informative, but it's not enough.
